name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  cicd:
    runs-on: ubuntu-latest
     steps:
    - uses: actions/checkout@v3
			with:
				ref: "dev"
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: Deploy to aws s3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-north-east-2"
          SOURCE_DIR: "build"
